Save Recorded Subject
Sensors-in-Paradise/android-native-xsens pull request #76
Opened 2021-12-14 13:04 UTC by kpostnov

Closes #61.

![Screenshot_20211214-125734](https://user-images.githubusercontent.com/41285083/146002843-b1f39fc4-f620-4256-a977-e288e02d1da7.png)

## Changes
This PR adds a second spinner to select the recorded subject. The file structure was adapted as well. 
Starting a recording is now only possible when both - activity and person - are selected.

## Further
The text view showing the amout of recordings per label could be modified by differentiating between different subjects.
However, I did not think there was a need for this.

2021-12-14 16:38 UTC, lucasliebe requested changes
Please remove one added log statement in RecordingDataManager.kt line 17.

I also dont think there is a need for counting recordings per person, it doesnt add value.

Thanks for removing comments and artifacts.

The way you abstracted the Spinners looks good but since many code seems similar maybe there is a way to move some lines of setUpSpinnerPeople and setUpSpinnerActivity to another function to remove code duplication. Please speak up if you think this is wrong.

2022-01-03 09:22 UTC, tfiedlerdev requested changes
Working on it as coordinated with @lucasliebe . Replacing spinners with Textfield/edittext that opens dialog on click

2022-01-03 16:42 UTC, tfiedlerdev approved these changes

2022-01-05 09:37 UTC, lucasliebe approved these changes

2022-01-05 12:15 UTC, merged